
name: Google Sheets Update

on:
  schedule:
    - cron: "31 0 * * *"  # Daily at 00:30 UTC
  workflow_dispatch: {}

jobs:
  update_gsheets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Google Sheets sync
      run: python scripts/main/data/gsheets_sync.py
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        CRYPTO_SPREADSHEET_KEY: ${{ secrets.CRYPTO_SPREADSHEET_KEY }}
