
name: Google Sheets Update

on:
  schedule:
    - cron: "31 0 * * *"  # Daily at 00:30 UTC
  workflow_dispatch: {}

jobs:
  update_gsheets:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Run structure validation tests
      run: |
        python tests/test_path_structure.py

    - name: Run Google Sheets update script
      run: python scripts/main/gsheets.py
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}


  
