name: gsheet_update_figma


on:
  schedule:
    - cron: "31 * * * *"  # Daily at 00:30 UTC
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          virtual-environment: 'venv'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn mysql-connector-python sqlalchemy requests psycopg2-binary gspread oauth2client gspread-dataframe

      - name: Set Google Sheets Key
        run: |
          echo "GOOGLE_SHEETS_KEY=$(secrets.IAM_GOOGLE_KEY)" >> $GITHUB_ENV

      - name: Run Python script
        run: |
          source venv/bin/activate  # Activate the virtual environment
          python gsheets.py
          env:
            IAM_GOOGLE_KEY: ${{ secrets.IAM_GOOGLE_KEY}}

