name: gsheet_update_figma


on:
  schedule:
    - cron: "31 * * * *"  # Daily at 00:30 UTC
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install pandas numpy matplotlib seaborn mysql-connector-python sqlalchemy requests psycopg2-binary gspread oauth2client gspread-dataframe


    - name: Run gsheets script
      run: |
        source venv/bin/activate  # Ensure virtual environment is activated
        python gsheets.py  # Run the Python script
      env:
        IAM_GOOGLE_KEY: ${{ secrets.IAM_GOOGLE_KEY }}  # Pass the secret to the script
