name: Instagram Mega-Carousel Daily Post

on:
  schedule:
    - cron: "0 2 * * *"  # Daily at 02:00 UTC
  workflow_dispatch: {}  # Allow manual trigger

jobs:
  generate_and_post_mega_carousel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv requests
        playwright install chromium
      env:
        PYTHONIOENCODING: utf-8

    - name: Generate and Post Mega-Carousel (14 slides)
      run: python scripts/main/publishing/post_mega_carousel.py
      env:
        PYTHONIOENCODING: utf-8
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        CRYPTO_SPREADSHEET_KEY: ${{ secrets.CRYPTO_SPREADSHEET_KEY }}
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}

    - name: Upload artifacts (if needed)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: instagram-outputs
        path: |
          output_html/*.html
          output_images/*.jpg
        retention-days: 7
