name: Path Check

on:
  workflow_dispatch:

jobs:
  post_story:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents for debugging
        run: |
          echo "Listing contents of the root directory"
          ls -la
          echo "Listing contents of instagram directory"
          ls -la instagram
